import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
    # "~/.config/alacritty/themes/themes/solarized_light.toml"
]

[window]
dimensions = { columns = 200, lines = 60 }
option_as_alt = "Both"

